---
Build:
  Name: Marsh Example Website
  Description: Yet Another Example Website
  URL: https://bradleysepos.github.io/marsh-example
  Path: public
  Targets:
    - Name:   Marsh Example Website
      Path:   .
      Force:  true
      Source: source/*
      Template:
        Source: ../templates/default
        #Overrides:
        #  - ../templates/default/template-overrides.yaml
    - Name:   About Marsh Example
      Path:   about
      Force:  true
      Source: source/about
      Template:
        Source: ../templates/default
        #Overrides:
        #  - ../templates/default/template-overrides.yaml
    - Name:   Marsh Example News
      Path:   news
      Force:  true
      Source: source/news
      Template:
        Source: ../templates/default
        #Overrides:
        #  - ../templates/default/template-overrides.yaml
      Archives:
        - Name:     Marsh Example News
          Path:     index.markdown
          #Encoding: html
          #Count:    10
          Types:    [ news ]
          Exclude_States: [ draft ]
        - Name:     Marsh Example News
          Path:     feed.xml
          Encoding: atom
          #Count:    10
          Types:    [ news ]
          Exclude_States: [ draft ]
        - Name:     Marsh Example News
          Path:     feed.json
          Encoding: json
          #Count:    10
          Types:    [ news ]
          Exclude_States: [ draft ]
...
