---
Build:
  Name: Marsh Example Site
  Description: Example static website built with marsh
  URL: https://bradleysepos.github.io/marsh-example
  Path: public
  Targets:
    - Name:   Marsh Example Site
      Path:   .
      Force:  true
      Source: source/*
      Sitemap: site-map/index.markdown
      Template:
        Source: ../templates/example
        #Overrides:
        #  - ../templates/example/template-overrides.yaml
      Archives:
        - Name:      News Archive
          Path:      news/index.markdown
          Root_Path: news
          Encoding:  html
          Page_Size: 10
          Types:     [ news ]
          Exclude_States: [ draft ]
          #Template:
          #  Source: ../templates/example
          #  Overrides:
          #    - ../templates/example/template-overrides.yaml
        - Name:      Full News Archive
          Path:      news/all/index.markdown
          Root_Path: news
          Encoding:  html
          Types:     [ news ]
          Exclude_States:  [ draft ]
        - Name:      Marsh News Feed
          Path:      news/feed.xml
          Root_Path: news
          Encoding:  atom
          Count:     20
          Types:     [ news ]
          Exclude_States: [ draft ]
        - Name:      Marsh News Feed
          Path:      news/feed.json
          Root_Path: news
          Encoding:  json
          Count:     20
          Types:     [ news ]
          Exclude_States: [ draft ]
...
