#!/usr/bin/env bash
# marsh-test - marsh unit tests
#
# Copyright 2026 Bradley Sepos
# Released under the MIT License. See LICENSE for details.
# https://github.com/bradleysepos/marsh

NAME="marsh-test"
SELF="${BASH_SOURCE[0]}"
SELF_DIR=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd -P)
SELF_DIR="${SELF_DIR:-$(pwd)}"
SELF_NAME=$(basename "${SELF}")
SYS_NAME=$(uname | awk '{ print tolower($0)}')
HELP="\
usage: ${SELF_NAME} [-h | --help]
       ${SELF_NAME} [--marsh marsh] [test_name[,...]]
where:
  -h, --help
        display this help text
  --marsh
        path to marsh
        default: marsh (system PATH)"

# args
MARSH=""
OPTIND=1
OPTSPEC=":-:h"
OPTARRAY=('-h' '--help' '--marsh')  # all short and long options
while getopts "${OPTSPEC}" OPT; do
    case "${OPT}" in
        -)
            case "${OPTARG}" in
                help)
                    # Print help and exit
                    echo -e "${HELP}"
                    exit 0
                    ;;
                help=*)
                    # Print help and exit
                    echo -e "${HELP}"
                    exit 0
                    ;;
                marsh)
                    if [[ -z ${!OPTIND+isset} ]]; then
                        # Option without required argument
                        echo "Option --${OPTARG} requires a value" >&2
                        echo -e "${HELP}"
                        exit 1
                    fi
                    MARSH="${!OPTIND}"
                    OPTIND=$((OPTIND + 1))
                    ;;
                marsh=*)
                    MARSH="${OPTARG#*=}"
                    ;;
                *)
                    if [[ "${OPTERR}" == 1 ]]; then
                        # Invalid option specified
                        echo "Invalid option: --${OPTARG}" >&2
                        echo -e "${HELP}"
                        exit 1
                    fi
                    ;;
            esac
            ;;
        h)
            # Print help and exit
            echo -e "${HELP}"
            exit 0
            ;;
        :)
            # Option without required value
            echo "Option -${OPTARG} requires a value" >&2
            echo -e "${HELP}"
            exit 1
            ;;
        \?)
            # Invalid option specified
            echo "Invalid option: -${OPTARG}" >&2
            echo -e "${HELP}"
            exit 1
            ;;
    esac
done
shift $((OPTIND - 1))

# dependencies
if [[ "${MARSH}" != "" ]] && [[ "${MARSH#\/}" == "${MARSH}" ]]; then
    MARSH="$(pwd -P)/${MARSH}"
fi
MARSH="${MARSH:-marsh}"
MARSH_FOUND=false
if echo "${MARSH}" | grep '/' >/dev/null 2>&1; then
    if [[ -x "${MARSH}" ]]; then
        MARSH_FOUND=true
    fi
elif hash "${MARSH}" >/dev/null 2>&1; then
    MARSH_FOUND=true
fi
if [[ "${MARSH_FOUND}" == false ]]; then
    echo "Error: marsh not found at '${MARSH}'" >&2
    exit 1
fi

# temp dir
TEMP_DIR="${TMPDIR:-/tmp}"
TEMP_DIR="${TEMP_DIR%/}"
MARSH_TEST_TEMP=$(mktemp -d "${TEMP_DIR}/marsh-test-XXXXXX" 2>/dev/null)
if [[ ! -d "${MARSH_TEST_TEMP}" ]]; then
    echo "Error: unable to create test temporary directory" >&2
    exit 1
fi
function marsh_test_cleanup {
    rm -rf "${MARSH_TEST_TEMP}"
}
trap marsh_test_cleanup EXIT

function marsh_test_group {
    local FUNCTION_NAME="${1}" ERRORS TEST_ID RES
    ERRORS=0
    for TEST_ID in $(seq 0 99); do
        marsh_test "${FUNCTION_NAME}:${TEST_ID}"
        RES=$?
        if [[ "${RES}" -eq 1 ]]; then
            ERRORS=$((ERRORS + 1))
        elif [[ "${RES}" -eq 2 ]]; then
            break
        fi
    done
    return "${ERRORS}"
}

function marsh_test {
    local TEST_NAME="${1}" EXISTS TEST EXPECTED RES
    local TEST_TEMP_PREFIX SOURCE_FILE META_FILE CONTENT_FILE
    EXISTS=true
    TEST=""
    EXPECTED=""
    RES="[FAIL]"
    TEST_TEMP_PREFIX="${MARSH_TEST_TEMP}/${TEST_NAME//[:]/-}"
    case "${TEST_NAME}" in
        marsh_get_variables:0)
            TEST_NAME+=":single"
            TEST=$(echo "FOO=foo" | marsh_get_variables)
            EXPECTED="FOO"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_get_variables:1)
            TEST_NAME+=":multiple"
            TEST=$(echo "FOO=foo"$'\n'"BAR=bar" | marsh_get_variables)
            EXPECTED="BAR"$'\n'"FOO"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_flat_to_array:0)
            TEST_NAME+=":nested"
            TEST=$(FOOBAR_0="foo" FOOBAR_1="bar" FOOBAR_X="x" marsh_flat_to_array "ARRAY" "FOOBAR_")
            EXPECTED="ARRAY=()"$'\n'"ARRAY+=(\"foo\")"$'\n'"ARRAY+=(\"bar\")"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_in_array:0)
            TEST_NAME+=":false"
            $(marsh_in_array "baz" "foo" "bar")
            TEST=$?
            EXPECTED=1
            if [[ "${TEST}" -eq "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_in_array:1)
            TEST_NAME+=":true"
            $(marsh_in_array "baz" "foo" "bar" "baz")
            TEST=$?
            EXPECTED=0
            if [[ "${TEST}" -eq "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_parse_yaml:0)
            TEST_NAME+=":map"
            TEST=$(marsh_parse_yaml "FOO: foo" "PREFIX")
            EXPECTED="PREFIX_FOO=\"foo\""
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_parse_yaml:1)
            TEST_NAME+=":map"
            TEST=$(marsh_parse_yaml "FOO: foo"$'\n'"BAR: bar" "PREFIX")
            EXPECTED="PREFIX_FOO=\"foo\""$'\n'"PREFIX_BAR=\"bar\""
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_parse_yaml:2)
            TEST_NAME+=":map_sequence"
            TEST=$(marsh_parse_yaml "EMPTY: []" "PREFIX")
            EXPECTED=""
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_parse_yaml:3)
            TEST_NAME+=":map_sequence"
            TEST=$(marsh_parse_yaml "FOOBAR: [foo, bar]" "PREFIX")
            EXPECTED="PREFIX_FOOBAR_0=\"foo\""$'\n'"PREFIX_FOOBAR_1=\"bar\""
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_parse_yaml:4)
            TEST_NAME+=":map_sequence"
            TEST=$(marsh_parse_yaml "FOOBAR:"$'\n'"  - foo"$'\n'"  - bar" "PREFIX")
            EXPECTED="PREFIX_FOOBAR=\"\""$'\n'"PREFIX_FOOBAR_0=\"foo\""$'\n'"PREFIX_FOOBAR_1=\"bar\""
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_parse_yaml:5)
            TEST_NAME+=":map_sequence"
            TEST=$(marsh_parse_yaml "FOOBAR:"$'\n'"  - foo"$'\n'"  - bar: [baz]" "PREFIX")
            EXPECTED="PREFIX_FOOBAR=\"\""$'\n'"PREFIX_FOOBAR_0=\"foo\""$'\n'"PREFIX_FOOBAR_1_bar_0=\"baz\""
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_parse_yaml:6)
            TEST_NAME+=":quoted"
            TEST=$(marsh_parse_yaml "FOO: \"foo bar\"" "PREFIX")
            EXPECTED="PREFIX_FOO=\"foo bar\""
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_parse_yaml:7)
            TEST_NAME+=":indent"
            TEST=$(marsh_parse_yaml "FOO:"$'\n'"    BAR: baz" "PREFIX" 4)
            EXPECTED="PREFIX_FOO=\"\""$'\n'"PREFIX_FOO_BAR=\"baz\""
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_has_frontmatter:0)
            TEST_NAME+=":true"
            SOURCE_FILE="${TEST_TEMP_PREFIX}.source.markdown"
            printf '%s\n' '---' 'Title: Example' '---' '' 'Body text' > "${SOURCE_FILE}"
            $(marsh_has_frontmatter "${SOURCE_FILE}")
            TEST=$?
            EXPECTED=0
            rm -f "${SOURCE_FILE}"
            if [[ "${TEST}" -eq "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_has_frontmatter:1)
            TEST_NAME+=":false"
            SOURCE_FILE="${TEST_TEMP_PREFIX}.source.markdown"
            printf '%s\n' 'Title: Example' '' 'Body text' > "${SOURCE_FILE}"
            $(marsh_has_frontmatter "${SOURCE_FILE}")
            TEST=$?
            EXPECTED=1
            rm -f "${SOURCE_FILE}"
            if [[ "${TEST}" -eq "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_extract_frontmatter:0)
            TEST_NAME+=":success"
            SOURCE_FILE="${TEST_TEMP_PREFIX}.source.markdown"
            META_FILE="${TEST_TEMP_PREFIX}.meta.yaml"
            CONTENT_FILE="${TEST_TEMP_PREFIX}.content.markdown"
            printf '%s\n' '---' 'Title: Example' 'Tags: [one, two]' '---' '' 'Body text' > "${SOURCE_FILE}"
            marsh_extract_frontmatter "${SOURCE_FILE}" "${META_FILE}" "${CONTENT_FILE}"
            TEST="$?"
            EXPECTED="0"
            if [[ "${TEST}" -eq "${EXPECTED}" ]]; then
                TEST="$(<"${META_FILE}")"$'\001'"$(<"${CONTENT_FILE}")"
                EXPECTED='---'$'\n''Title: Example'$'\n''Tags: [one, two]'$'\n''...'$'\001'$'\n''Body text'
            fi
            rm -f "${SOURCE_FILE}" "${META_FILE}" "${CONTENT_FILE}"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_extract_frontmatter:1)
            TEST_NAME+=":empty_body"
            SOURCE_FILE="${TEST_TEMP_PREFIX}.source.markdown"
            META_FILE="${TEST_TEMP_PREFIX}.meta.yaml"
            CONTENT_FILE="${TEST_TEMP_PREFIX}.content.markdown"
            printf '%s\n' '---' 'Title: Example' '---' > "${SOURCE_FILE}"
            marsh_extract_frontmatter "${SOURCE_FILE}" "${META_FILE}" "${CONTENT_FILE}"
            TEST="$?"
            EXPECTED="0"
            if [[ "${TEST}" -eq "${EXPECTED}" ]]; then
                TEST="$(<"${META_FILE}")"$'\001'"$(<"${CONTENT_FILE}")"
                EXPECTED='---'$'\n''Title: Example'$'\n''...'$'\001'
            fi
            rm -f "${SOURCE_FILE}" "${META_FILE}" "${CONTENT_FILE}"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_extract_frontmatter:2)
            TEST_NAME+=":missing"
            SOURCE_FILE="${TEST_TEMP_PREFIX}.source.markdown"
            META_FILE="${TEST_TEMP_PREFIX}.meta.yaml"
            CONTENT_FILE="${TEST_TEMP_PREFIX}.content.markdown"
            printf '%s\n' 'Title: Example' '' 'Body text' > "${SOURCE_FILE}"
            marsh_extract_frontmatter "${SOURCE_FILE}" "${META_FILE}" "${CONTENT_FILE}"
            TEST="$?"
            EXPECTED="1"
            rm -f "${SOURCE_FILE}" "${META_FILE}" "${CONTENT_FILE}"
            if [[ "${TEST}" -eq "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_resolve_tag_metadata:0)
            TEST_NAME+=":generated"
            TEST=$(marsh_resolve_tag_metadata "document.uri" "DOCUMENT_")
            EXPECTED="TAG_VAR=DOCUMENT_URI"$'\n'"TAG_TYPE=string"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_resolve_tag_metadata:1)
            TEST_NAME+=":known"
            TEST=$(marsh_resolve_tag_metadata "document.title" "DOCUMENT_")
            EXPECTED="TAG_VAR=DOCUMENT_Title"$'\n'"TAG_TYPE=string"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_resolve_tag_metadata:2)
            TEST_NAME+=":known"
            TEST=$(marsh_resolve_tag_metadata "document.project-version" "DOCUMENT_" "DOCUMENT_Title"$'\n'"DOCUMENT_Project_Version")
            EXPECTED="TAG_VAR=DOCUMENT_Project_Version"$'\n'"TAG_TYPE=string"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_resolve_tag_metadata:3)
            TEST_NAME+=":known"
            TEST=$(marsh_resolve_tag_metadata "document.authors" "SUBDOCUMENT_")
            EXPECTED="TAG_VAR=SUBDOCUMENT_Authors_"$'\n'"TAG_TYPE=array"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_resolve_tag_metadata:4)
            TEST_NAME+=":custom"
            TEST=$(marsh_resolve_tag_metadata "document.custom-thing" "DOCUMENT_" "DOCUMENT_Custom_Thing")
            EXPECTED="TAG_VAR=DOCUMENT_Custom_Thing"$'\n'"TAG_TYPE=string"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_resolve_tag_metadata:5)
            TEST_NAME+=":nonexistent"
            TEST=$(marsh_resolve_tag_metadata "document.foo" "DOCUMENT_" 2>/dev/null)
            TEST=$?
            EXPECTED=1
            if [[ "${TEST}" -eq "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_resolve_tag_metadata:6)
            TEST_NAME+=":ambiguous"
            TEST=$(marsh_resolve_tag_metadata "document.foo-bar" "DOCUMENT_" "DOCUMENT_Foo_Bar"$'\n'"DOCUMENT_FOO_BAR" 2>/dev/null)
            TEST=$?
            EXPECTED=1
            if [[ "${TEST}" -eq "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:0)
            TEST_NAME+=":append"
            TEST=$(echo "Some text"$'\n'"More text" | marsh_text_filter append:after)
            EXPECTED="Some text"$'\n'"More text"$'\n'"after"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:1)
            TEST_NAME+=":date_rfc2822"
            TEST=$(echo "2022-02-22" | marsh_text_filter date:rfc2822)
            EXPECTED="Tue, 22 Feb 2022 00:00:00 +0000"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:2)
            TEST_NAME+=":date_rfc2822"
            TEST=$(echo "2022-02-22 02:02:02" | marsh_text_filter date:rfc2822)
            EXPECTED="Tue, 22 Feb 2022 02:02:02 +0000"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:3)
            TEST_NAME+=":date_rfc3339"
            TEST=$(echo "2022-02-22" | marsh_text_filter date:rfc3339)
            EXPECTED="2022-02-22T00:00:00+00:00"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:4)
            TEST_NAME+=":date_rfc3339"
            TEST=$(echo "2022-02-22 02:02:02" | marsh_text_filter date:rfc3339)
            EXPECTED="2022-02-22T02:02:02+00:00"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:5)
            TEST_NAME+=":date"
            TEST=$(echo "2022-02-22" | marsh_text_filter date)
            EXPECTED="2022-02-22"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:6)
            TEST_NAME+=":date"
            TEST=$(echo "2022-02-22 02:02:02" | marsh_text_filter date)
            EXPECTED="2022-02-22"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:7)
            TEST_NAME+=":decode_entities"
            TEST=$(echo "Some entities to decode: &lt; &gt; &amp; &#34; &#165; &#9829;" | marsh_text_filter decode:entities)
            EXPECTED="Some entities to decode: < > & \" ¥ ♥"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:8)
            TEST_NAME+=":email_remove_angle_addr"
            TEST=$(echo "John Doe <john.doe@example.com> (jdoe42)"$'\n\n'"<john.doe@example.com>"$'\n\n'"<p>Some HTML <span>content</span></p>" | marsh_text_filter email:remove-angle-addr)
            # According to RFC 2822, angle-addr seems to be valid only as part of name-addr
            # and invalid as a standalone addr-spec wrapped in angle brackets
            EXPECTED="John Doe (jdoe42)"$'\n\n'"<john.doe@example.com>"$'\n\n'"<p>Some HTML <span>content</span></p>"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:9)
            TEST_NAME+=":escape_html"
            TEST=$(echo "<div><p>Some HTML content<br><br /></p></div>" | marsh_text_filter escape:html)
            EXPECTED="&lt;div&gt;&lt;p&gt;Some HTML content&lt;br&gt;&lt;br /&gt;&lt;/p&gt;&lt;/div&gt;"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:10)
            TEST_NAME+=":escape_json_val"
            TEST=$(echo "{ \"key\": \"value\" }" | marsh_text_filter escape:json-val)
            EXPECTED="{ \\\"key\\\": \\\"value\\\" }"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:11)
            TEST_NAME+=":escape_nbsp"
            TEST=$(echo "Some text with spaces" | marsh_text_filter escape:nbsp)
            EXPECTED="Some&nbsp;text&nbsp;with&nbsp;spaces"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:12)
            TEST_NAME+=":excerpt"
            TEST=$(echo "Lorem ipsum dolor sit amet, consectetur adipiscing elit."$'\n\n'"The quick brown fox jumps over the lazy dog." | marsh_text_filter excerpt:300:1)
            EXPECTED="Lorem ipsum dolor sit amet, consectetur adipiscing elit."
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:13)
            TEST_NAME+=":excerpt"
            TEST=$(echo "Lorem ipsum dolor sit amet, consectetur adipiscing elit."$'\n\n'"The quick brown fox jumps over the lazy dog." | marsh_text_filter excerpt:76:2)
            EXPECTED="Lorem ipsum dolor sit amet, consectetur adipiscing elit. The quick brown fox"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:14)
            TEST_NAME+=":hash_md5"
            TEST=$(echo -n "foobar" | marsh_text_filter hash:md5)
            EXPECTED="3858f62230ac3c915f300c664312c63f"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:15)
            TEST_NAME+=":headings_push"
            TEST=$(echo "Heading 1"$'\n'"========="$'\n\n'"Heading 2"$'\n'"---------"$'\n\n'"Paragraph" | marsh_text_filter headings:push)
            EXPECTED="## Heading 1"$'\n\n'"### Heading 2"$'\n\n'"Paragraph"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:16)
            TEST_NAME+=":headings_push"
            TEST=$(echo "# Heading 1"$'\n\n'"## Heading 2"$'\n\n'"### Heading 3"$'\n\n'"#### Heading 4"$'\n\n'"##### Heading 5"$'\n\n'"###### Heading 6"$'\n\n'"Paragraph" | marsh_text_filter headings:push)
            EXPECTED="## Heading 1"$'\n\n'"### Heading 2"$'\n\n'"#### Heading 3"$'\n\n'"##### Heading 4"$'\n\n'"###### Heading 5"$'\n\n'"**Heading 6**"$'\n\n'"Paragraph"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:17)
            TEST_NAME+=":headings_push"
            TEST=$(echo "<h1>Heading 1</h1><h2>Heading 2</h2><h3>Heading 3</h3><h4>Heading 4</h4><h5>Heading 5</h5><h6>Heading 6</h6><p>Paragraph</p>" | marsh_text_filter headings:push)
            EXPECTED="<h2>Heading 1</h2><h3>Heading 2</h3><h4>Heading 3</h4><h5>Heading 4</h5><h6>Heading 5</h6><strong>Heading 6</strong><p>Paragraph</p>"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:18)
            TEST_NAME+=":headings_shift"
            TEST=$(echo "Heading 1"$'\n'"========="$'\n\n'"Heading 2"$'\n'"---------"$'\n\n'"Paragraph" | marsh_text_filter headings:shift)
            EXPECTED="# Heading 2"$'\n\n'"Paragraph"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:19)
            TEST_NAME+=":headings_shift"
            TEST=$(echo "# Heading 1"$'\n\n'"## Heading 2"$'\n\n'"### Heading 3"$'\n\n'"#### Heading 4"$'\n\n'"##### Heading 5"$'\n\n'"###### Heading 6"$'\n\n'"Paragraph" | marsh_text_filter headings:shift)
            EXPECTED="# Heading 2"$'\n\n'"## Heading 3"$'\n\n'"### Heading 4"$'\n\n'"#### Heading 5"$'\n\n'"##### Heading 6"$'\n\n'"Paragraph"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:20)
            TEST_NAME+=":headings_shift"
            TEST=$(echo "<h1>Heading 1</h1><h2>Heading 2</h2><h3>Heading 3</h3><h4>Heading 4</h4><h5>Heading 5</h5><h6>Heading 6</h6><p>Paragraph</p>" | marsh_text_filter headings:shift)
            EXPECTED="<h1>Heading 2</h1><h2>Heading 3</h2><h3>Heading 4</h3><h4>Heading 5</h4><h5>Heading 6</h5><p>Paragraph</p>"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:21)
            TEST_NAME+=":headings_remove"
            TEST=$(echo "Heading 1"$'\n'"========="$'\n\n'"Heading 2"$'\n'"---------"$'\n\n'"Paragraph" | marsh_text_filter headings:remove)
            EXPECTED="Paragraph"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:22)
            TEST_NAME+=":headings_remove"
            TEST=$(echo "# Heading 1"$'\n\n'"## Heading 2"$'\n\n'"### Heading 3"$'\n\n'"#### Heading 4"$'\n\n'"##### Heading 5"$'\n\n'"###### Heading 6"$'\n\n'"Paragraph" | marsh_text_filter headings:remove)
            EXPECTED="Paragraph"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:23)
            TEST_NAME+=":headings_remove"
            TEST=$(echo "<h1>Heading 1</h1><h2>Heading 2</h2><h3>Heading 3</h3><h4>Heading 4</h4><h5>Heading 5</h5><h6>Heading 6</h6><p>Paragraph</p>" | marsh_text_filter headings:remove)
            EXPECTED="<p>Paragraph</p>"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:24)
            TEST_NAME+=":items_append"
            TEST=$(echo "Some text"$'\n'"More text" | marsh_text_filter items:append:\!)
            EXPECTED="Some text!"$'\n'"More text!"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:25)
            TEST_NAME+=":items_append"
            TEST=$(echo "Some text"$'\n'"More text" | marsh_text_filter 'items:append:\\\:')
            EXPECTED='Some text\:'$'\n'"More text\:"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:26)
            TEST_NAME+=":items_count"
            TEST=$(echo "foo"$'\n'"bar"$'\n'"baz" | marsh_text_filter items:count)
            EXPECTED="3"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:27)
            TEST_NAME+=":items_first"
            TEST=$(echo "foo"$'\n'"bar"$'\n'"baz" | marsh_text_filter items:first)
            EXPECTED="foo"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:28)
            TEST_NAME+=":items_join"
            TEST=$(echo "I am foo"$'\n'"I am bar"$'\n'"I am baz" | marsh_text_filter items:join)
            EXPECTED="I am fooI am barI am baz"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:29)
            TEST_NAME+=":items_join"
            TEST=$(echo "I am foo"$'\n'"I am bar"$'\n'"I am baz" | marsh_text_filter items:join:,)
            EXPECTED="I am foo,I am bar,I am baz"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:30)
            TEST_NAME+=":items_join"
            TEST=$(echo "I am foo"$'\n'"I am bar"$'\n'"I am baz" | marsh_text_filter 'items:join:, : and :, and ')
            EXPECTED="I am foo, I am bar, and I am baz"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:31)
            TEST_NAME+=":items_join"
            TEST=$(echo "I am foo"$'\n'"I am bar" | marsh_text_filter 'items:join:, : and :, and ')
            EXPECTED="I am foo and I am bar"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:32)
            TEST_NAME+=":items_join"
            TEST=$(echo "I am foo"$'\n'"I am bar"$'\n'"I am baz" | marsh_text_filter 'items:join:\:')
            EXPECTED="I am foo:I am bar:I am baz"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:33)
            TEST_NAME+=":items_join"
            TEST=$(echo "I am foo"$'\n'"I am bar" | marsh_text_filter 'items:join:\\\:')
            EXPECTED='I am foo\:I am bar'
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:34)
            TEST_NAME+=":items_join_type_oxford"
            TEST=$(echo "I am foo"$'\n'"I am bar" | marsh_text_filter items:join-type:oxford)
            EXPECTED="I am foo and I am bar"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:35)
            TEST_NAME+=":items_join_type_oxford"
            TEST=$(echo "I am foo"$'\n'"I am bar"$'\n'"I am baz" | marsh_text_filter items:join-type:oxford)
            EXPECTED="I am foo, I am bar, and I am baz"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:36)
            TEST_NAME+=":items_json_array"
            TEST=$(echo "John Doe"$'\n'"Jane Doe" | marsh_text_filter items:json-array)
            EXPECTED='"John Doe","Jane Doe"'
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:37)
            TEST_NAME+=":items_json_array"
            TEST=$(echo "John Doe"$'\n'"Jane Doe" | marsh_text_filter items:json-array:name)
            EXPECTED='{"name":"John Doe"},{"name":"Jane Doe"}'
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:38)
            TEST_NAME+=":items_json_array"
            TEST=$(echo "John Doe"$'\n\n'"Jane Doe" | marsh_text_filter items:json-array)
            EXPECTED='"John Doe","Jane Doe"'
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:39)
            TEST_NAME+=":items_json_array"
            TEST=$(printf '%s\n%s' 'John "JD" Doe' $'C:\\Users\tjd' | marsh_text_filter items:json-array)
            EXPECTED="\"John \\\"JD\\\" Doe\",\"C:\\\\Users\\tjd\""
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:40)
            TEST_NAME+=":items_json_array"
            TEST=$(echo "John Doe" | marsh_text_filter 'items:json-array:we"ird\key')
            EXPECTED='{"we\"ird\\key":"John Doe"}'
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:41)
            TEST_NAME+=":items_last"
            TEST=$(echo "foo"$'\n'"bar"$'\n'"baz" | marsh_text_filter items:last)
            EXPECTED="baz"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:42)
            TEST_NAME+=":items_prepend"
            TEST=$(echo "Some text"$'\n'"More text" | marsh_text_filter items:prepend:\!)
            EXPECTED="!Some text"$'\n'"!More text"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:43)
            TEST_NAME+=":items_prepend"
            TEST=$(echo "Some text"$'\n'"More text" | marsh_text_filter 'items:prepend:\\\:')
            EXPECTED='\:Some text'$'\n'"\:More text"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:44)
            TEST_NAME+=":items_slice"
            TEST=$(echo "foo"$'\n'"bar"$'\n'"baz"$'\n'"qux" | marsh_text_filter items:slice:2:3)
            EXPECTED="bar"$'\n'"baz"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:45)
            TEST_NAME+=":items_slice"
            TEST=$(echo "foo"$'\n'"bar"$'\n'"baz"$'\n'"qux" | marsh_text_filter items:slice:3)
            EXPECTED="baz"$'\n'"qux"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:46)
            TEST_NAME+=":items_sort"
            TEST=$(echo "charlie"$'\n'"alpha"$'\n'"bravo" | marsh_text_filter items:sort)
            EXPECTED="alpha"$'\n'"bravo"$'\n'"charlie"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:47)
            TEST_NAME+=":items_trim"
            # Add a delimiter after filters have been appliedto preserve trailing newlines
            # in the test variable, and afterward remove it using parameter expansion
            TEST=$(printf '%s' $'\n\n\n\n'"           # Heading 1"$'\n\n\n\n'"Paragraph"$'\t\n\n\n\n'"    " | marsh_text_filter items:trim; printf '\001')
            TEST="${TEST%$'\001'}"
            EXPECTED=$'\n\n\n\n'"# Heading 1"$'\n\n\n\n'"Paragraph"$'\n\n\n\n'""
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:48)
            TEST_NAME+=":items_unique"
            TEST=$(echo "foo"$'\n'"bar"$'\n'"foo"$'\n'"baz"$'\n'"bar" | marsh_text_filter items:unique)
            EXPECTED="foo"$'\n'"bar"$'\n'"baz"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:49)
            TEST_NAME+=":items_wrap"
            TEST=$(echo "Some text"$'\n'"More text" | marsh_text_filter items:wrap:\")
            EXPECTED="\"Some text\""$'\n'"\"More text\""
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:50)
            TEST_NAME+=":items_wrap"
            TEST=$(echo "Some text"$'\n'"More text" | marsh_text_filter items:wrap:\":\!\")
            EXPECTED="\"Some text!\""$'\n'"\"More text!\""
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:51)
            TEST_NAME+=":items_wrap"
            TEST=$(echo "Some text"$'\n'"More text" | marsh_text_filter 'items:wrap:\:')
            EXPECTED=":Some text:"$'\n'":More text:"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:52)
            TEST_NAME+=":items_wrap"
            TEST=$(echo "Some text"$'\n'"More text" | marsh_text_filter 'items:wrap:\\\:')
            EXPECTED='\:Some text\:'$'\n'"\:More text\:"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:53)
            TEST_NAME+=":items_xml_wrap"
            TEST=$(echo $'\n\n\n'"John Doe"$'\n\n\n' | marsh_text_filter items:xml-wrap:name)
            EXPECTED='<name>John Doe</name>'
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:54)
            TEST_NAME+=":items_xml_wrap"
            TEST=$(echo "John Doe"$'\n'"Jane Doe" | marsh_text_filter items:xml-wrap:name)
            EXPECTED='<name>John Doe</name><name>Jane Doe</name>'
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:55)
            TEST_NAME+=":items_xml_wrap"
            TEST=$(echo "John Doe"$'\n\n\n'"Jane Doe" | marsh_text_filter items:xml-wrap:name)
            EXPECTED='<name>John Doe</name><name>Jane Doe</name>'
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:56)
            TEST_NAME+=":items_xml_wrap"
            TEST=$(echo "Jack & Jill <friends>" | marsh_text_filter items:xml-wrap:person)
            EXPECTED='<person>Jack &amp; Jill &lt;friends&gt;</person>'
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:57)
            TEST_NAME+=":items_xml_wrap"
            TEST=$(echo "John Doe"$'\n'"Jane Doe" | marsh_text_filter items:xml-wrap:name:author)
            EXPECTED='<author><name>John Doe</name></author><author><name>Jane Doe</name></author>'
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:58)
            TEST_NAME+=":items_xml_wrap"
            TEST=$(echo "John Doe"$'\n'"Jane Doe" | marsh_text_filter items:xml-wrap:name:author:people)
            EXPECTED='<people><author><name>John Doe</name></author></people><people><author><name>Jane Doe</name></author></people>'
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:59)
            TEST_NAME+=":links_replace_ext"
            TEST=$(echo "[foo](foo.markdown) [foo](foo.md) [foo](foo.text) [foo](foo.md \"title\") [![image](image.jpg)](imagepage.md) [![image](image.jpg) \"title\"](imagepage.md) [![image](image.jpg)](imagepage.md \"title\") [![image](image.jpg) \"title\"](imagepage.md \"title\")"$'\n\n'"[1]: reference1.md"$'\n'"[2]: reference2.md \"title\""$'\n'"[3]: reference3.md#anchor \"title\""$'\n'"[4label]: reference4.md?qs=qs&qs2=qs2#anchor 'title'"$'\n'"[label5]: <reference5.md?qs=qs&qs2=qs2#anchor> (title)" | marsh_text_filter links:replace-ext:md,markdown:html)
            EXPECTED="[foo](foo.html) [foo](foo.html) [foo](foo.text) [foo](foo.html \"title\") [![image](image.jpg)](imagepage.html) [![image](image.jpg) \"title\"](imagepage.html) [![image](image.jpg)](imagepage.html \"title\") [![image](image.jpg) \"title\"](imagepage.html \"title\")"$'\n\n'"[1]: reference1.html"$'\n'"[2]: reference2.html \"title\""$'\n'"[3]: reference3.html#anchor \"title\""$'\n'"[4label]: reference4.html?qs=qs&qs2=qs2#anchor 'title'"$'\n'"[label5]: <reference5.html?qs=qs&qs2=qs2#anchor> (title)"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:60)
            TEST_NAME+=":links_replace_ext"
            TEST=$(echo "[foo](foo.markdown) [foo](foo.md) [foo](foo.text)" | marsh_text_filter links:replace-ext:md,markdown)
            EXPECTED="[foo](foo) [foo](foo) [foo](foo.text)"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:61)
            TEST_NAME+=":newlines_reduce"
            TEST=$(echo "# Heading 1"$'\n\n\n\n\n\n'"Paragraph" | marsh_text_filter newlines:reduce:3)
            EXPECTED="# Heading 1"$'\n\n\n'"Paragraph"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:62)
            TEST_NAME+=":newlines_remove"
            TEST=$(echo "# Heading 1"$'\n\n\n\n'"Paragraph" | marsh_text_filter newlines:remove)
            EXPECTED="# Heading 1Paragraph"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:63)
            TEST_NAME+=":newlines_tospaces"
            TEST=$(echo "# Heading 1"$'\n\n\n\n'"Paragraph" | marsh_text_filter newlines:tospaces)
            EXPECTED="# Heading 1    Paragraph"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:64)
            TEST_NAME+=":newlines_trim"
            TEST=$(echo $'\n\n\n\n'"# Heading 1"$'\n\n\n\n'"Paragraph"$'\n\n\n\n' | marsh_text_filter newlines:trim)
            EXPECTED="# Heading 1"$'\n\n\n\n'"Paragraph"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:65)
            TEST_NAME+=":plaintext"
            TEST=$(echo "<div><p>Some HTML content and entities to decode: &lt; &gt; &amp; &#34; &#165; &#9829;<br><br /></p></div>" | marsh_text_filter plaintext)
            EXPECTED="Some HTML content and entities to decode: < > & \" ¥ ♥"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:66)
            TEST_NAME+=":plaintext"
            TEST=$(echo "Raw < character should work on BSD sed" | marsh_text_filter plaintext)
            EXPECTED="Raw < character should work on BSD sed"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:67)
            TEST_NAME+=":prepend"
            TEST=$(echo "Some text"$'\n'"More text" | marsh_text_filter prepend:before)
            EXPECTED="before"$'\n'"Some text"$'\n'"More text"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:68)
            TEST_NAME+=":slug"
            TEST=$(echo "Title of something" | marsh_text_filter slug)
            EXPECTED="title-of-something"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:69)
            TEST_NAME+=":wrap"
            TEST=$(echo "Some text"$'\n\n'"More text" | marsh_text_filter wrap:before:after)
            EXPECTED="before"$'\n\n'"Some text"$'\n\n'"More text"$'\n\n'"after"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:70)
            TEST_NAME+=":wrap_type_special_comment"
            TEST=$(echo "Some text"$'\n\n'"<p>Some HTML</p>" | marsh_text_filter wrap-type:special-comment:div.wrapper)
            EXPECTED="<!-- div.wrapper -->"$'\n\n'"Some text"$'\n\n'"<p>Some HTML</p>"$'\n\n'"<!-- /div.wrapper -->"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:71)
            TEST_NAME+=":multiple"
            TEST=$(echo $'\n\n\n\n'"Some text"$'\n'"&#9829;" | marsh_text_filter newlines:trim newlines:tospaces decode:entities items:wrap:\")
            EXPECTED="\"Some text ♥\""
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:72)
            TEST_NAME+=":multiple"
            TEST=$(echo "First item"$'\n'"Second item"$'\n'"Third item" | marsh_text_filter items:slice:1 escape:nbsp items:wrap:\" items:join-type:oxford)
            EXPECTED="\"First&nbsp;item\", \"Second&nbsp;item\", and \"Third&nbsp;item\""
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        *)
            EXISTS=false
            ;;
    esac
    if [[ "${FUNCNAME[1]}" == "marsh_test_group" ]] && [[ "${EXISTS}" != true ]]; then
        return 2
    fi
    echo -n "${RES}"$'\t'"${TEST_NAME}"
    if [[ "${EXISTS}" == true ]]; then
        if [[ "${RES}" == "[FAIL]" ]]; then
            echo $'\t'"Expected: \`${EXPECTED//$'\n'/\\n}\` Actual: \`${TEST//$'\n'/\\n}\`"
            return 1
        fi
        echo ""
        return 0
    fi
    echo $'\t'"Test not found"
    return 1
}

source "${MARSH}"
KNOWN_FUNCTIONS=(
    marsh_extract_frontmatter
    marsh_flat_to_array
    marsh_get_variables
    marsh_has_frontmatter
    marsh_in_array
    marsh_parse_yaml
    marsh_resolve_tag_metadata
    marsh_text_filter
)
FUNCTIONS=("${@}")
if [[ "${FUNCTIONS[*]}" == "" ]]; then
    FUNCTIONS=("${KNOWN_FUNCTIONS[@]}")
fi
echo "Running tests: ${FUNCTIONS[*]}"
ERRORS=false
for FUNCTION in "${FUNCTIONS[@]}"; do
    if [[ " ${KNOWN_FUNCTIONS[*]} " =~ " ${FUNCTION//:*/} " ]]; then
        if [[ "${FUNCTION}" == "${FUNCTION//:*/}" ]]; then
            marsh_test_group "${FUNCTION}" || ERRORS=true
        else
            marsh_test "${FUNCTION}" || ERRORS=true
        fi
    else
        echo "[FAIL]"$'\t'"${FUNCTION}"$'\t'"Function for test not found" && ERRORS=true
    fi
done
if [[ "${ERRORS}" == true ]]; then
    echo "Some tests are failing."
    exit 1
fi
echo "All tests are passing."
exit 0
