#!/usr/bin/env bash
# marsh-test - marsh unit tests
#
# Copyright 2026 Bradley Sepos
# Released under the MIT License. See LICENSE for details.
# https://github.com/bradleysepos/marsh

NAME="marsh-test"
SELF="${BASH_SOURCE[0]}"
SELF_DIR=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd -P)
SELF_DIR="${SELF_DIR:-$(pwd)}"
SELF_NAME=$(basename "${SELF}")
SYS_NAME=$(uname | awk '{ print tolower($0)}')
HELP="\
usage: ${SELF_NAME} [-h | --help]
       ${SELF_NAME} [--marsh marsh] [test_name[,...]]
where:
  -h, --help
        display this help text
  --marsh
        path to marsh
        default: marsh (system PATH)"

# args
MARSH=""
OPTIND=1
OPTSPEC=":-:h"
OPTARRAY=('-h' '--help' '--marsh')  # all short and long options
while getopts "${OPTSPEC}" OPT; do
    case "${OPT}" in
        -)
            case "${OPTARG}" in
                help)
                    # Print help and exit
                    echo -e "${HELP}"
                    exit 0
                    ;;
                help=*)
                    # Print help and exit
                    echo -e "${HELP}"
                    exit 0
                    ;;
                marsh)
                    if [[ -z ${!OPTIND+isset} ]]; then
                        # Option without required argument
                        echo "Option --${OPTARG} requires a value" >&2
                        echo -e "${HELP}"
                        exit 1
                    fi
                    MARSH="${!OPTIND}"
                    OPTIND=$((OPTIND + 1))
                    ;;
                marsh=*)
                    MARSH="${OPTARG#*=}"
                    ;;
                *)
                    if [[ "${OPTERR}" == 1 ]]; then
                        # Invalid option specified
                        echo "Invalid option: --${OPTARG}" >&2
                        echo -e "${HELP}"
                        exit 1
                    fi
                    ;;
            esac
            ;;
        h)
            # Print help and exit
            echo -e "${HELP}"
            exit 0
            ;;
        :)
            # Option without required value
            echo "Option -${OPTARG} requires a value" >&2
            echo -e "${HELP}"
            exit 1
            ;;
        \?)
            # Invalid option specified
            echo "Invalid option: -${OPTARG}" >&2
            echo -e "${HELP}"
            exit 1
            ;;
    esac
done
shift $((OPTIND - 1))

# dependencies
if [[ "${MARSH}" != "" ]] && [[ "${MARSH#\/}" == "${MARSH}" ]]; then
    MARSH="$(pwd -P)/${MARSH}"
fi
MARSH="${MARSH:-marsh}"
MARSH_FOUND=false
if echo "${MARSH}" | grep '/' >/dev/null 2>&1; then
    if [[ -x "${MARSH}" ]]; then
        MARSH_FOUND=true
    fi
elif hash "${MARSH}" >/dev/null 2>&1; then
    MARSH_FOUND=true
fi
if [[ "${MARSH_FOUND}" == false ]]; then
    echo "Error: marsh not found at '${MARSH}'" >&2
    exit 1
fi

function marsh_test_group {
    local FUNCTION_NAME="${1}" ERRORS TEST_ID RES
    ERRORS=0
    for TEST_ID in $(seq 0 99); do
        marsh_test "${FUNCTION_NAME}:${TEST_ID}"
        RES=$?
        if [[ "${RES}" -eq 1 ]]; then
            ERRORS=$((ERRORS + 1))
        elif [[ "${RES}" -eq 2 ]]; then
            break
        fi
    done
    return "${ERRORS}"
}

function marsh_test {
    local TEST_NAME="${1}" EXISTS TEST EXPECTED RES
    EXISTS=true
    TEST=""
    EXPECTED=""
    RES="[FAIL]"
    case "${TEST_NAME}" in
        marsh_get_variables:0)
            TEST_NAME+=":single"
            TEST=($(echo "FOO=foo" | marsh_get_variables))
            TEST="${TEST[*]}"
            EXPECTED="FOO"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_get_variables:1)
            TEST_NAME+=":multiple"
            TEST=($(echo "FOO=foo"$'\n'"BAR=bar" | marsh_get_variables))
            TEST="${TEST[*]}"
            EXPECTED="BAR FOO"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_flat_to_array:0)
            TEST_NAME+=":nested"
            TEST=($(FOOBAR_0="foo" FOOBAR_1="bar" FOOBAR_X="x" marsh_flat_to_array "ARRAY" "FOOBAR_"))
            TEST="${TEST[*]}"
            EXPECTED="ARRAY=() ARRAY+=(\"foo\") ARRAY+=(\"bar\")"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_in_array:0)
            TEST_NAME+=":false"
            $(marsh_in_array "baz" "foo" "bar")
            TEST=$?
            EXPECTED=1
            if [[ "${TEST}" -eq "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_in_array:1)
            TEST_NAME+=":true"
            $(marsh_in_array "baz" "foo" "bar" "baz")
            TEST=$?
            EXPECTED=0
            if [[ "${TEST}" -eq "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_join_delimited:0)
            TEST_NAME+=":comma"
            TEST=$(marsh_join_delimited "," "," "," "foo" "bar" "baz")
            EXPECTED="foo,bar,baz"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_join_delimited:1)
            TEST_NAME+=":comma_and"
            TEST=$(marsh_join_delimited ", " " and " ", and " "foo" "bar" "baz")
            EXPECTED="foo, bar, and baz"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_join_delimited:2)
            TEST_NAME+=":and"
            TEST=$(marsh_join_delimited ", " " and " ", and " "foo" "bar")
            EXPECTED="foo and bar"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_md5_string:0)
            TEST_NAME+=":hash"
            TEST=$(marsh_md5_string "foobar")
            EXPECTED="3858f62230ac3c915f300c664312c63f"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_parse_yaml:0)
            TEST_NAME+=":map"
            TEST=($(marsh_parse_yaml "FOO: foo" "PREFIX"))
            TEST="${TEST[*]}"
            EXPECTED="PREFIX_FOO=\"foo\""
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_parse_yaml:1)
            TEST_NAME+=":map"
            TEST=($(marsh_parse_yaml "FOO: foo"$'\n'"BAR: bar" "PREFIX"))
            TEST="${TEST[*]}"
            EXPECTED="PREFIX_FOO=\"foo\" PREFIX_BAR=\"bar\""
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_parse_yaml:2)
            TEST_NAME+=":map_sequence"
            TEST=($(marsh_parse_yaml "EMPTY: []" "PREFIX"))
            TEST="${TEST[*]}"
            EXPECTED=""
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_parse_yaml:3)
            TEST_NAME+=":map_sequence"
            TEST=($(marsh_parse_yaml "FOOBAR: [foo, bar]" "PREFIX"))
            TEST="${TEST[*]}"
            EXPECTED="PREFIX_FOOBAR_0=\"foo\" PREFIX_FOOBAR_1=\"bar\""
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_parse_yaml:4)
            TEST_NAME+=":map_sequence"
            TEST=($(marsh_parse_yaml "FOOBAR:"$'\n'"  - foo"$'\n'"  - bar" "PREFIX"))
            TEST="${TEST[*]}"
            EXPECTED="PREFIX_FOOBAR=\"\" PREFIX_FOOBAR_0=\"foo\" PREFIX_FOOBAR_1=\"bar\""
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_parse_yaml:5)
            TEST_NAME+=":map_sequence"
            TEST=($(marsh_parse_yaml "FOOBAR:"$'\n'"  - foo"$'\n'"  - bar: [baz]" "PREFIX"))
            TEST="${TEST[*]}"
            EXPECTED="PREFIX_FOOBAR=\"\" PREFIX_FOOBAR_0=\"foo\" PREFIX_FOOBAR_1_bar_0=\"baz\""
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:0)
            TEST_NAME+=":date_rfc3339"
            TEST=$(echo "2022-02-22" | marsh_text_filter date:rfc3339)
            EXPECTED="2022-02-22T00:00:00+00:00"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:1)
            TEST_NAME+=":date_rfc3339"
            TEST=$(echo "2022-02-22 02:02:02" | marsh_text_filter date:rfc3339)
            EXPECTED="2022-02-22T02:02:02+00:00"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:2)
            TEST_NAME+=":date_rfc2822"
            TEST=$(echo "2022-02-22" | marsh_text_filter date:rfc2822)
            EXPECTED="Tue, 22 Feb 2022 00:00:00 +0000"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:3)
            TEST_NAME+=":date_rfc2822"
            TEST=$(echo "2022-02-22 02:02:02" | marsh_text_filter date:rfc2822)
            EXPECTED="Tue, 22 Feb 2022 02:02:02 +0000"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:4)
            TEST_NAME+=":date"
            TEST=$(echo "2022-02-22" | marsh_text_filter date)
            EXPECTED="2022-02-22"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:5)
            TEST_NAME+=":date"
            TEST=$(echo "2022-02-22 02:02:02" | marsh_text_filter date)
            EXPECTED="2022-02-22"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:6)
            TEST_NAME+=":decode_entities"
            TEST=$(echo "Some entities to decode: &lt; &gt; &amp; &#34; &#165; &#9829;" | marsh_text_filter decode:entities)
            EXPECTED="Some entities to decode: < > & \" ¥ ♥"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:7)
            TEST_NAME+=":escape_html"
            TEST=$(echo "<div><p>Some HTML content<br><br /></p></div>" | marsh_text_filter escape:html)
            EXPECTED="&lt;div&gt;&lt;p&gt;Some HTML content&lt;br&gt;&lt;br /&gt;&lt;/p&gt;&lt;/div&gt;"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:8)
            TEST_NAME+=":escape_json_val"
            TEST=$(echo "{ \"key\": \"value\" }" | marsh_text_filter escape:json-val)
            EXPECTED="{ \\\"key\\\": \\\"value\\\" }"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:9)
            TEST_NAME+=":excerpt"
            TEST=$(echo "Lorem ipsum dolor sit amet, consectetur adipiscing elit."$'\n\n'"The quick brown fox jumps over the lazy dog." | marsh_text_filter excerpt:300:1)
            EXPECTED="Lorem ipsum dolor sit amet, consectetur adipiscing elit."
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:10)
            TEST_NAME+=":excerpt"
            TEST=$(echo "Lorem ipsum dolor sit amet, consectetur adipiscing elit."$'\n\n'"The quick brown fox jumps over the lazy dog." | marsh_text_filter excerpt:76:2)
            EXPECTED="Lorem ipsum dolor sit amet, consectetur adipiscing elit. The quick brown fox"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:11)
            TEST_NAME+=":headings_push"
            TEST=$(echo "Heading 1"$'\n'"========="$'\n\n'"Heading 2"$'\n'"---------"$'\n\n'"Paragraph" | marsh_text_filter headings:push)
            EXPECTED="## Heading 1"$'\n\n'"### Heading 2"$'\n\n'"Paragraph"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:12)
            TEST_NAME+=":headings_push"
            TEST=$(echo "# Heading 1"$'\n\n'"## Heading 2"$'\n\n'"### Heading 3"$'\n\n'"#### Heading 4"$'\n\n'"##### Heading 5"$'\n\n'"###### Heading 6"$'\n\n'"Paragraph" | marsh_text_filter headings:push)
            EXPECTED="## Heading 1"$'\n\n'"### Heading 2"$'\n\n'"#### Heading 3"$'\n\n'"##### Heading 4"$'\n\n'"###### Heading 5"$'\n\n'"**Heading 6**"$'\n\n'"Paragraph"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:13)
            TEST_NAME+=":headings_push"
            TEST=$(echo "<h1>Heading 1</h1><h2>Heading 2</h2><h3>Heading 3</h3><h4>Heading 4</h4><h5>Heading 5</h5><h6>Heading 6</h6><p>Paragraph</p>" | marsh_text_filter headings:push)
            EXPECTED="<h2>Heading 1</h2><h3>Heading 2</h3><h4>Heading 3</h4><h5>Heading 4</h5><h6>Heading 5</h6><strong>Heading 6</strong><p>Paragraph</p>"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:14)
            TEST_NAME+=":headings_shift"
            TEST=$(echo "Heading 1"$'\n'"========="$'\n\n'"Heading 2"$'\n'"---------"$'\n\n'"Paragraph" | marsh_text_filter headings:shift)
            EXPECTED="# Heading 2"$'\n\n'"Paragraph"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:15)
            TEST_NAME+=":headings_shift"
            TEST=$(echo "# Heading 1"$'\n\n'"## Heading 2"$'\n\n'"### Heading 3"$'\n\n'"#### Heading 4"$'\n\n'"##### Heading 5"$'\n\n'"###### Heading 6"$'\n\n'"Paragraph" | marsh_text_filter headings:shift)
            EXPECTED="# Heading 2"$'\n\n'"## Heading 3"$'\n\n'"### Heading 4"$'\n\n'"#### Heading 5"$'\n\n'"##### Heading 6"$'\n\n'"Paragraph"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:16)
            TEST_NAME+=":headings_shift"
            TEST=$(echo "<h1>Heading 1</h1><h2>Heading 2</h2><h3>Heading 3</h3><h4>Heading 4</h4><h5>Heading 5</h5><h6>Heading 6</h6><p>Paragraph</p>" | marsh_text_filter headings:shift)
            EXPECTED="<h1>Heading 2</h1><h2>Heading 3</h2><h3>Heading 4</h3><h4>Heading 5</h4><h5>Heading 6</h5><p>Paragraph</p>"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:17)
            TEST_NAME+=":headings_remove"
            TEST=$(echo "Heading 1"$'\n'"========="$'\n\n'"Heading 2"$'\n'"---------"$'\n\n'"Paragraph" | marsh_text_filter headings:remove)
            EXPECTED="Paragraph"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:18)
            TEST_NAME+=":headings_remove"
            TEST=$(echo "# Heading 1"$'\n\n'"## Heading 2"$'\n\n'"### Heading 3"$'\n\n'"#### Heading 4"$'\n\n'"##### Heading 5"$'\n\n'"###### Heading 6"$'\n\n'"Paragraph" | marsh_text_filter headings:remove)
            EXPECTED="Paragraph"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:19)
            TEST_NAME+=":headings_remove"
            TEST=$(echo "<h1>Heading 1</h1><h2>Heading 2</h2><h3>Heading 3</h3><h4>Heading 4</h4><h5>Heading 5</h5><h6>Heading 6</h6><p>Paragraph</p>" | marsh_text_filter headings:remove)
            EXPECTED="<p>Paragraph</p>"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:20)
            TEST_NAME+=":links_replace_ext"
            TEST=$(echo "[foo](foo.markdown) [foo](foo.md) [foo](foo.text) [foo](foo.md \"title\") [![image](image.jpg)](imagepage.md) [![image](image.jpg) \"title\"](imagepage.md) [![image](image.jpg)](imagepage.md \"title\") [![image](image.jpg) \"title\"](imagepage.md \"title\")"$'\n\n'"[1]: reference1.md"$'\n'"[2]: reference2.md \"title\""$'\n'"[3]: reference3.md#anchor \"title\""$'\n'"[4label]: reference4.md?qs=qs&qs2=qs2#anchor 'title'"$'\n'"[label5]: <reference5.md?qs=qs&qs2=qs2#anchor> (title)" | marsh_text_filter links:replace-ext:md,markdown:html)
            EXPECTED="[foo](foo.html) [foo](foo.html) [foo](foo.text) [foo](foo.html \"title\") [![image](image.jpg)](imagepage.html) [![image](image.jpg) \"title\"](imagepage.html) [![image](image.jpg)](imagepage.html \"title\") [![image](image.jpg) \"title\"](imagepage.html \"title\")"$'\n\n'"[1]: reference1.html"$'\n'"[2]: reference2.html \"title\""$'\n'"[3]: reference3.html#anchor \"title\""$'\n'"[4label]: reference4.html?qs=qs&qs2=qs2#anchor 'title'"$'\n'"[label5]: <reference5.html?qs=qs&qs2=qs2#anchor> (title)"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:21)
            TEST_NAME+=":links_replace_ext"
            TEST=$(echo "[foo](foo.markdown) [foo](foo.md) [foo](foo.text)" | marsh_text_filter links:replace-ext:md,markdown)
            EXPECTED="[foo](foo) [foo](foo) [foo](foo.text)"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:22)
            TEST_NAME+=":newlines_reduce"
            TEST=$(echo "# Heading 1"$'\n\n\n\n'"Paragraph" | marsh_text_filter newlines:reduce)
            EXPECTED="# Heading 1"$'\n\n'"Paragraph"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:23)
            TEST_NAME+=":newlines_remove"
            TEST=$(echo "# Heading 1"$'\n\n\n\n'"Paragraph" | marsh_text_filter newlines:remove)
            EXPECTED="# Heading 1Paragraph"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:24)
            TEST_NAME+=":newlines_tospaces"
            TEST=$(echo "# Heading 1"$'\n\n\n\n'"Paragraph" | marsh_text_filter newlines:tospaces)
            EXPECTED="# Heading 1    Paragraph"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:25)
            TEST_NAME+=":newlines_trim"
            TEST=$(echo $'\n\n\n\n'"# Heading 1"$'\n\n\n\n'"Paragraph"$'\n\n\n\n' | marsh_text_filter newlines:trim)
            EXPECTED="# Heading 1"$'\n\n\n\n'"Paragraph"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:26)
            TEST_NAME+=":plaintext"
            TEST=$(echo "<div><p>Some HTML content and entities to decode: &lt; &gt; &amp; &#34; &#165; &#9829;<br><br /></p></div>" | marsh_text_filter plaintext)
            EXPECTED="Some HTML content and entities to decode: < > & \" ¥ ♥"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:27)
            TEST_NAME+=":slug"
            TEST=$(echo "Title of something" | marsh_text_filter slug)
            EXPECTED="title-of-something"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:28)
            TEST_NAME+=":whitespace_trim"
            TEST=$(echo $'\n\n\n\n'"           # Heading 1"$'\n\n\n\n'"Paragraph"$'\t\n\n\n\n'"    " | marsh_text_filter whitespace:trim)
            EXPECTED="# Heading 1"$'\n\n\n\n'"Paragraph"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:29)
            TEST_NAME+=":wrap"
            TEST=$(echo "Some text"$'\n\n'"<p>Some HTML</p>" | marsh_text_filter wrap:special-comment:div.wrapper)
            EXPECTED="<!-- div.wrapper -->"$'\n\n'"Some text"$'\n\n'"<p>Some HTML</p>"$'\n\n'"<!-- /div.wrapper -->"
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:30)
            TEST_NAME+=":wrap"
            TEST=$(echo "Some text" | marsh_text_filter wrap:\")
            EXPECTED="\"Some text\""
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:31)
            TEST_NAME+=":wrap"
            TEST=$(echo "Some text" | marsh_text_filter wrap:\":\!\")
            EXPECTED="\"Some text!\""
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        marsh_text_filter:32)
            TEST_NAME+=":multiple"
            TEST=$(echo $'\n\n\n\n'"Some text"$'\n'"&#9829;" | marsh_text_filter newlines:trim newlines:tospaces decode:entities wrap:\")
            EXPECTED="\"Some text ♥\""
            if [[ "${TEST}" == "${EXPECTED}" ]]; then
                RES="[PASS]"
            fi
            ;;
        *)
            EXISTS=false
            ;;
    esac
    if [[ "${FUNCNAME[1]}" == "marsh_test_group" ]] && [[ "${EXISTS}" != true ]]; then
        return 2
    fi
    echo -n "${RES}"$'\t'"${TEST_NAME}"
    if [[ "${EXISTS}" == true ]]; then
        if [[ "${RES}" == "[FAIL]" ]]; then
            echo $'\t'"Expected: \`${EXPECTED//$'\n'/\\n}\` Actual: \`${TEST//$'\n'/\\n}\`"
            return 1
        fi
        echo ""
        return 0
    fi
    echo $'\t'"Test not found"
    return 1
}

source "${MARSH}"
KNOWN_FUNCTIONS=(
    marsh_flat_to_array
    marsh_get_variables
    marsh_in_array
    marsh_join_delimited
    marsh_md5_string
    marsh_parse_yaml
    marsh_text_filter
)
FUNCTIONS=("${@}")
if [[ "${FUNCTIONS[*]}" == "" ]]; then
    FUNCTIONS=("${KNOWN_FUNCTIONS[@]}")
fi
echo "Running tests: ${FUNCTIONS[*]}"
ERRORS=false
for FUNCTION in "${FUNCTIONS[@]}"; do
    if [[ " ${KNOWN_FUNCTIONS[*]} " =~ " ${FUNCTION//:*/} " ]]; then
        if [[ "${FUNCTION}" == "${FUNCTION//:*/}" ]]; then
            marsh_test_group "${FUNCTION}" || ERRORS=true
        else
            marsh_test "${FUNCTION}" || ERRORS=true
        fi
    else
        echo "[FAIL]"$'\t'"${FUNCTION}"$'\t'"Function for test not found" && ERRORS=true
    fi
done
if [[ "${ERRORS}" == true ]]; then
    echo "Some tests are failing."
    exit 1
fi
echo "All tests are passing."
exit 0
